### ISSUE TITLE
Logging in with the recovery key, still prompts you to insert your recovery key

### ISSUE THREAD

**Issue by Velin92** [element-hq/element-x-ios#3618]
### Steps to reproduce

1. Log out or fresh install
2. Log in with an existing account for which you have the recovery key
3. Use the recovery key to restore your backups
4. Key is valid and succesfully verified (you wil get the modal telling you about it)
5. Land on the home screen/room list

#### What did you expect?
To see the room list without any backup banner

#### What happened instead?
I see the room list but the banner about my key storage being out of sync appears. It should not be appearing, or necessary for me to input my recovery key again, since I have already logged in and verified by using it. However I have to say that by inserting my recovery key again, the banner goes away. But still, it's weird for the user to insert their recovery key twice.

### Your phone model

iPhone Simulator

### Operating system version

18.1

### Application version

1.9.10

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I believe we fixed some bugs around this recently, please reopen if not the case.

**Comment by jk0v** [comment]
@stefanceriu I don't have permission to reopen this issue, but I have the same issue.

On both the Android and IPadOS versions of Element X (both 25.02.0), I logged in, verified the client and entered my recovery key.
The app confirmed the recovery key, but still said that key storage was out of sync. 

I therefore have no way of loading my old encryption keys and see my old messages.

**Comment by stefanceriu** [comment]
Interesting, it might very well be that you crypto setup is broken somehow. Can you please sumit a rageshake so we can have a look at the logs?

In the past these problems have been fixed by asking the user to resetting their cross-signing and trying again. Would be lovely if you could test that, if it's not too much of hassle for you 🙏

**Comment by jk0v** [comment]
I reset the cross-signing and reverified my devices as you suggested.
On the IPad version the problem went away, but the problem persists on Android (or maybe it'll work with some time?)

Here is the log I copied after reverifying and entering the recovery key on Android.
Thanks for the help so far.
[logs.2025-02-27-23.log](https://github.com/user-attachments/files/19017594/logs.2025-02-27-23.log)

**Comment by stefanceriu** [comment]
I can't speak to the android specific logs but the sdk seems to have correctly detected the identity change

```
2025-02-27T23:00:19.014646Z  INFO matrix_sdk::encryption::recovery: Recovery state changed from Unknown to Incomplete | crates/matrix-sdk/src/encryption/recovery/mod.rs:629 | spans: keys_query{request_id="4c61fe1531f749f08719307ce2ca6a34" device_keys={"@jk0v:matrix.org": []}} > update_state_after_keys_query

2025-02-27T23:00:19.016824Z  WARN matrix_sdk_crypto::identities::manager: Our own device might have been deleted user_id="@jk0v:matrix.org" device_id="PWJHMXCWRH" curve25519_key="curve25519:PDCrnKYFbz4WwUPRqULqNBwQNB2/0z4N71gLAWgPjgw" ed25519_key="ed25519:21BR136GckGMuJjzSvG5JA5u5zBp0hSQm17rOfBm9Tk" | crates/matrix-sdk-crypto/src/identities/manager.rs:348

2025-02-27T23:00:19.074604Z  WARN matrix_sdk_crypto::identities::manager: Our own device might have been deleted user_id="@jk0v:matrix.org" device_id="PWJHMXCWRH" curve25519_key="curve25519:PDCrnKYFbz4WwUPRqULqNBwQNB2/0z4N71gLAWgPjgw" ed25519_key="ed25519:21BR136GckGMuJjzSvG5JA5u5zBp0hSQm17rOfBm9Tk" | crates/matrix-sdk-crypto/src/identities/manager.rs:348

2025-02-27T23:00:19.356101Z  WARN matrix_sdk_crypto::backups: Trying to backup room keys but no backup key was found | crates/matrix-sdk-crypto/src/backups/mod.rs:520

2025-02-27T23:00:19.382343Z  WARN matrix_sdk_crypto::machine: Failed to decrypt a room event: Can't find the room key to decrypt the event
```

... and then it's all downhill from there.

Perhaps a fresh login on android is the thing that's needed here.

As for the original ticket, I'm going to go out on a limb here and say that your other client didn't set things up the right way initially. If it's element web then it's probably from before it switched over to the rust sdk crypto.

**Comment by jh72de** [comment]
Same here in fresh Element X install on Android. Entering key works fine, but unsynched warning box stays.
