### ISSUE TITLE
New message marker (fully_read) is frequently at wrong location

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#4184]
### Steps to reproduce

1. open room
2. scroll up until new marker is visible
3. notice you didn't see the messages above yet

### Outcome

With the following account data according to EW dev tools:
```json
{
  "type": "m.fully_read",
  "content": {
    "event_id": "$Kbh_MizSVNbR_tetg-rTu7Zk3B1-xiGOZkm4gwdNFy4"
  }
}
```
#### What did you expect?
Marker directly below the event stored in m.fully_read room account data or the last visible one. In this case this would be above the "Hello!" from Linux Renaissance. The pointed to event is an `m.room.member` event.
![Image](https://github.com/user-attachments/assets/5f834e3d-d9be-477e-8e67-0567cc4830f6)

#### What happened instead?
![Image](https://github.com/user-attachments/assets/840b3d13-7f8d-4004-b490-1a771f6a662e)

### Your phone model

iPhone 13 mini

### Operating system version

iOS 18.5

### Application version

25.06.2 (172)

### Homeserver

Synapse 1.131.0

### Will you send logs?

Yes

**Comment by marwing** [comment]
I tried but failed to send logs (see #4185 for details). If you need logs for this, please let me know and I'll try to find and send them manually somehow (I'd like to avoid posting them publicly), or fix #4185 and I'll send them in-app.

**Comment by stefanceriu** [comment]
From my own testing element web seems to move the fully read marker (with some sort of delay) to the bottom of the timeline as you scroll through it and Element X updates accordingly. 

I would argue the behavior is wrong as it should set it to the top of the timeline while scrolling, until the bottom is reached and then mark the room as fully read.

I'll have a look at https://github.com/element-hq/element-x-ios/issues/4185 but there's slim chances logs would help here, too many moving parts to track correctly.

**Comment by marwing** [comment]
I would likely agree with your argument, particularly in light of https://github.com/element-hq/element-x-ios/issues/4177, which, if I interpret it correctly, breaks partially reading a room worse than it was before (something I'm going to test with the new nightly build).
The issue here, though, is that the room wasn't opened in EW before opening it in EX, and therefore the marker is indeed displayed at the wrong location. This has also happened with way more than three visible messages between the expected and actual marker positions.

Thanks for taking a look. In this case, I'll hold off on sending logs for now.

**Comment by pixlwave** [comment]
Fixed by #4177.

**Comment by marwing** [comment]
This was not actually fixed, I just verified with the nightly TF build. The issue is that the marker is rendered at the wrong location (some messages newer than it should be) according the the fully read marker in the room account data, not that that account data isn't updated. If I had to guess, I'd say the sdk timeline inserts it at the wrong location for some reason. 

I also found the marker missing if it would have been between collapsed state events. This is likely not an sdk issue, as I can see it in a different rust sdk ui based client (using the current 0.12.0 release of the sdk).

**Comment by pixlwave** [comment]
My bad, sorry @marwing, I'll re-open this issue.

**Comment by marwing** [comment]
This is really annoying. The divider is currently essentially useless. On my phone, when I see the marker, the actual last read event may be multiple screens away and if there are enough unread messages that within "multiple screens" is still useful information, the marker is way too easy to accidentally scroll past.
